#!/bin/sh

#beep

logger -t "device-server" "restart-all-servers called, $SSH_ORIGINAL_COMMAND"

cd $(dirname $0)
./down

sudo service vrpn stop
sudo service vrpn-leftglove stop
sudo service vrpn-rightglove stop

sleep 5

sudo service vrpn start
sudo service vrpn-leftglove start
sudo service vrpn-rightglove start

./up
#beep

