#!/bin/sh

# Three notes of a minor chord

A='-f 440'
C="-f 523.25"
E="-f 659.26"

whole='-l 2048'
dottedhalf='-l 1536'
half='-l 1024'
dottedquarter='-l 768'
quarter='-l 512'
dottedeighth='-l 384'
eighth='-l 256'
sixteenth='-l 128'

smallspace='-D 64'
longspace='-D 128'

beep \
	$eighth $E $smallspace -n \
	$eighth $C $smallspace -n \
	$quarter $A

