#!/bin/sh

# Three notes of a major chord

C='-f 523.25'
E='-f 659.26'
G='-f 783.99'

whole='-l 2048'
dottedhalf='-l 1536'
half='-l 1024'
dottedquarter='-l 768'
quarter='-l 512'
dottedeighth='-l 384'
eighth='-l 256'
sixteenth='-l 128'

smallspace='-D 64'
longspace='-D 128'

beep \
	$eighth $C $smallspace -n \
	$eighth $E $smallspace -n \
	$quarter $G

